### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/grandpa-scarer#9]
- [x] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [x] hardware.yml
- [x] software.yml
- [x] extras.yml
- [x] overview.md
- [x] learn.md

**Comment by bennuttall** [comment]
Missing components:

- [ ] [Big dome push button](http://proto-pic.co.uk/big-dome-push-button/)
- [ ] [Servo](http://proto-pic.co.uk/analogue-9-gram-servo/)
- [ ] Speaker

**Comment by bennuttall** [comment]
Cover added. Components incoming.

**Comment by bennuttall** [comment]
Learn is missing - is an empty file

**Comment by bennuttall** [comment]
Title of "bonus stuff" should be "what next?"

**Comment by bennuttall** [comment]
Step numbers need removing
